Exclude some macOS GHC versions because they fail to build
* 8.10.7

  ```
  <no location info>: error:
      Warning: Couldn't figure out LLVM version!
               Make sure you have installed LLVM between [9 and 13)
  ```

ghc: could not execute: opt

* 9.0.1

  ```
  Error: All install methods for ghc 9.0.1 failed
  ```

* 9.0.2

   ```
   <no location info>: error:
      Warning: Couldn't figure out LLVM version!
               Make sure you have installed LLVM between [9 and 13)
   ```

* 9.2.3

  ```
  Failed to build microaeson-0.1.0.1. The failure occurred during the configure
  step.
  Build log ( /Users/runner/.cabal/logs/ghc-9.2.3/mcrsn-0.1.0.1-39e5748c.log ):
  Error: cabal: Failed to build Cabal-syntax-3.12.0.0 (which is required by
  Configuring library for microaeson-0.1.0.1..
  Error: cabal-3.10.3.0: The program 'alex' version >=3.2.0 is required but the
  version of /Users/runner/.cabal/store/ghc-9.2.3/lx-3.5.1.0-e5169770/bin/alex
  could not be determined.

  test:stan-test from stan-0.1.2.1 and exe:stan from stan-0.1.2.1). The build
  process segfaulted (i.e. SIGSEGV).
  Failed to build microaeson-0.1.0.1 (which is required by test:stan-test from
  stan-0.1.2.1 and exe:stan from stan-0.1.2.1). See the build log above for
  details.
  ```

* 9.4.1

  ```
  Failed to build microaeson-0.1.0.1. The failure occurred during the configure
  step.
  Build log ( /Users/runner/.cabal/logs/ghc-9.4.1/mcrsn-0.1.0.1-910e64b6.log ):
  Configuring library for microaeson-0.1.0.1..
  Error: cabal-3.10.3.0: The program 'alex' version >=3.2.0 is required but the
  version of /Users/runner/.cabal/store/ghc-9.4.1/lx-3.5.1.0-92603e3d/bin/alex
  could not be determined.

  Error: cabal: Failed to build Cabal-syntax-3.12.0.0 (which is required by
  test:stan-test from stan-0.1.2.1 and exe:stan from stan-0.1.2.1). The build
  process segfaulted (i.e. SIGSEGV).
  Failed to build microaeson-0.1.0.1 (which is required by test:stan-test from
  stan-0.1.2.1 and exe:stan from stan-0.1.2.1). See the build log above for
  details.
  Failed to build pretty-show-1.10 (which is required by test:stan-test from
  stan-0.1.2.1). The build process segfaulted (i.e. SIGSEGV).
  ```