Bring release CI up to date
* Avoid setting environment directly because it is deprecated.  It
  causes the error

  Error: Unable to process command '::set-env
  name=BINARY_PATH::./dist/stan' successfully.

  Error: The `set-env` command is disabled. Please upgrade to using
  Environment Files or opt into unsecure command execution by setting
  the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to
  `true`. For more information see:
  https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

* Specify path to create for artifact download because of API change

  See https://github.com/actions/download-artifact#compatibility-between-v1-and-v2v3